export default {
    onbording1: require("./images/onBoarding.png"),
    onbording2: require("./images/onBoarding2.png"),
    onBoarding3: require("./images/onBoarding3.png"),
    homeIcon: require("./images/homeIcon.png"),
    addIcon: require("./images/addIcon.png"),
    SettingsIcon: require("./images/SettingsIcon.png"),
    containerIcon: require("./images/containerIcon.png"),
    water: require("./images/water.png"),
    Coffee: require("./images/Coffee.png"),
    Tea: require("./images/Tea.png"),
    Soda: require("./images/Soda.png"),
    Beer: require("./images/Beer.png"),
    Wine: require("./images/Wine.png"),
    Spirits: require("./images/Spirits.png"),
    Juice: require("./images/Juice.png"),
    Milk: require("./images/Milk.png"),
    camera: require("./images/camera.png"),
    dummyImage: require("./images/dummyImage.png"),
    logo: require("./images/logo.png"),
    editIcon: require("./images/editIcon.png"),
    backIcon: require("./images/backIcon.png"),
    lockIcon: require("./images/lockIcon.png"),
  };
  